<?php

function du_experts_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__find_an_expert' => [
      'render element' => 'elements',
      'base hook' => 'paragraph',
      'template' => 'paragraph--find-an-expert',
      'path' => $path . '/templates/paragraph',
    ],
    'views_view__find_an_expert' => [
      'base hook' => 'views_view',
      'template' => 'views-view--find-an-expert',
      'path' => $path . '/templates/views',
    ],
  ];
}

function du_experts_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  $paragraph = $variables['elements']['#paragraph'] ?? NULL;
  if ($paragraph && $paragraph->bundle() === 'find_an_expert') {
    $suggestions[] = 'paragraph__find_an_expert';
  }
}

function du_experts_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  $target_view_id = 'find_an_expert';
  $target_display_id = 'page_1';

  if ($view->id() === $target_view_id && $view->current_display === $target_display_id) {
    $suggestions[] = 'views_view__find_an_expert';
  }
}

function du_experts_preprocess_paragraph(array &$variables) {
  $paragraph = $variables['paragraph'] ?? NULL;

  if ($paragraph && $paragraph->bundle() === 'find_an_expert') {
    $variables['experts'] = $variables['content']['field_experts'] ?? [];
  }
}
